on: [push]

jobs:
  outputfiles:
    runs-on: ubuntu-latest
    name: Create output files
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: setup node
          uses: actions/setup-node@v3
        - name: execute
          working-directory: ./src
          run: npm install && node ./index.js save
        - name: commit
          uses: EndBug/add-and-commit@v9
          with:
            default_author: github_actions
            message: generated output
            tag_push: '--force'
